spring:
  application:
    name: hp-oj-user-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hp-oj-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true # 填写数据库名称
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  thymeleaf:
    cache: false
mybatis-plus:
  #mapper配置文件
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      id-type: assign_id # 雪花自增
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.pepedd.template.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
server:
  port: 8102
  servlet:
    context-path: /api
oss:
  aliyun:
    endpoint: ${oss.aliyun.endpoint} # 接入点
    project-name: ${oss.aliyun.project-name} # 项目名称
    access-key-id: ${oss.aliyun.access-key-id} # 访问密钥ID
    access-key-secret: ${oss.aliyun.access-key-secret} # 访问密钥密钥
    bucket-name: ${oss.aliyun.bucket-name} # 存储空间名称
    domain: ${oss.aliyun.domain} # 域名
knife4j:
  enable: true
sa-token:
  token-style: tik
  token-name: token
  timeout: 604800 # 7天
#  active-timeout: 1800 # 无操作 30分钟 自动过期
