spring:
  application:
    name: hp-oj-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 让gateway根据注册中心找到其他服务
          enabled: true
      routes:
        - id: hp-oj-user-service
          uri: lb://hp-oj-user-service
          predicates:
            - Path=/api/user/**,/api/auth/**
        - id: hp-oj-question-service
          uri: lb://hp-oj-question-service
          predicates:
            - Path=/api/question/**
        - id: hp-oj-judge-service
          uri: lb://hp-oj-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
